api_version: '1.21'
vnc_port: 6080
cmd_port: 6082

container_expire_secs: 90
queue_expire_secs: 30
remove_expired_secs: 20

image_prefix: netcapsule

default_browser: firefox

browsers:

    # firefox
    - id: firefox
      name: 'Mozilla Firefox'
      os: 'Linux'
      version: '40'
      icon: 'firefox.png'
      path: firefox

    # chrome
    - id: chrome
      name: 'Google Chrome'
      os: 'Linux'
      version: '46'
      icon: 'chrome.png'
      path: chrome

    # mosaic
    - id: mosaic
      name: 'NCSA Mosaic'
      os: 'Linux'
      version: '2.2'
      icon: 'mosaic.png'
      path: mosaic

    # netscape 
    - id: netscape
      name: 'Netscape Navigator'
      os: 'Linux'
      version: '4.79'
      icon: 'win32-ns4.png'
      path: nslinux

    - id: netscape4.8-win
      name: 'Netscape Navigator'
      os: 'Windows'
      version: '4.8'
      icon: 'win32-ns4.png'
      path: nswin
    
    - id: netscape-mac-3.04
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '3.04'
      icon: 'mac-ns2-3.png'
      path: nsmac3

    - id: netscape-mac-4.08
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '4.08'
      icon: 'mac-ns4.png'
      path: nsmac4

    - id: netscape4.8-mac
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '4.8'
      icon: 'mac-ns4.png'
      path: nsmac4.8

    # Internet Explorer
    - id: ie4.01-mac
      name: 'Internet Explorer'
      os: 'Macintosh'
      version: '4.01'
      icon: 'mac-ie4.png'
      path: ie4mac

    - id: ie5.1-mac
      name: 'Internet Explorer'
      os: 'Macintosh'
      version: '5.1.7'
      icon: 'mac-ie5.1.png'
      path: ie5mac

    - id: ie4
      name: 'Internet Explorer'
      os: 'Windows'
      version: '4.01'
      icon: 'win32-ie4.png'
      path: ie4

    - id: ie5.5
      name: 'Internet Explorer'
      os: 'Windows'
      version: '5.5'
      icon: 'win32-ie5.5.png'
      path: ie5.5

    # Safari
    - id: safari5
      name: 'Apple Safari'
      os: 'Windows'
      version: '5.0'
      icon: 'safari.png'
      path: safari
