api_version: '1.21'
vnc_port: 6080
cmd_port: 6082

container_expire_secs: 60
queue_expire_secs: 30
remove_expired_secs: 20

image_prefix: netcapsule

browsers:
    # firefox
    firefox: firefox
    ff: firefox

    # mosaic
    mosaic: mosaic

    # netscape linux  
    netscape: netscape

    # netscape win
    nswin4: netscape4.8-win
    ns: netscape4.8-win

    # netscape-mac
    nsmac3: netscape-mac-3.04
    
    nsmac: netscape-mac-4.08
    nsmac4: netscape-mac-4.08

    nsmac4.8: netscape4.8-mac

    # IE Mac
    ie4mac: ie4.01-mac
    ie5mac: ie5.1-mac

    # IE Win
    ie4: ie4
    ie5: ie5.5
    ie5.5: ie5.5
    ie: ie5.5

    # Safari
    safari: safari5
    safari5: safari

    # default
    '': firefox
