
vnc_port: 6080
cmd_port: 6082
redis_host: netcapsule_redis_1
pywb_host: netcapsule_pywb_1
api_version: '1.18'

container_expire_secs: 30
queue_expire_secs: 30
remove_expired_secs: 20

image_prefix: netcapsule

browsers:
    # firefox
    firefox: firefox
    ff: firefox

    # netscape    
    netscape: netscape
    ns: netscape

    # netscape-mac
    nsmac: netscape-mac-4.08

    # netscape-mac
    nsmac3: netscape-mac-3.04

    # IE Mac
    ie4mac: ie4.01-mac

    # mosaic
    mosaic: mosaic

    # IE
    ie4: ie4
    ie5.5: ie5.5
    ie: ie5.5

    # Safari
    safari: safari5
    safari5: safari

    # default
    '': firefox
