api_version: '1.21'
vnc_port: 6080
cmd_port: 6082

max_containers: 100

init_container_expire_secs: 30
full_container_expire_secs: 600

throttle_max_avg: 0.60
throttle_samples: 10
throttle_expire_secs: 60

queue_expire_secs: 30
remove_expired_secs: 30

image_prefix: webrecorder

default_browser: firefox

random_page_file: /app/urls.txt

redirect_paths:
    '': firefox
    'ie': ie5.5
    'ns': nswin
    'safari3': safari

browsers:

    # firefox
    - id: 'browser-firefox'
      name: 'Mozilla Firefox'
      os: 'Linux'
      version: '40'
      icon: 'firefox.png'
      path: firefox
      about: 'https://en.wikipedia.org/wiki/Firefox'

    # chrome
    - id: 'browser-chrome'
      name: 'Google Chrome'
      os: 'Linux'
      version: '46'
      icon: 'chrome.png'
      path: chrome
      about: 'https://en.wikipedia.org/wiki/Google_Chrome'

    - id: chromium5
      name: 'Chromium'
      os: 'Linux'
      version: '5'
      icon: 'chromium.png'
      path: chromium5
      about: 'https://en.wikipedia.org/wiki/Chromium_(web_browser)'

    - id: chromium10
      name: 'Chromium'
      os: 'Linux'
      version: '10'
      icon: 'chromium.png'
      path: chromium10
      about: 'https://en.wikipedia.org/wiki/Chromium_(web_browser)'
      skip_random: true

    # Lynx
    - id: lynx
      name: Lynx
      os: 'Linux'
      icon: 'lynx.png'
      path: lynx
      version: '2.8.9'
      about: 'https://en.wikipedia.org/wiki/Lynx_(web_browser)'
      skip_random: true

     # WWW
    - id: www
      name: 'WWW'
      os: 'NextSTEP'
      icon: 'next-www.png'
      path: WWW
      version: '1.0'
      about: 'https://en.wikipedia.org/wiki/WorldWideWeb'
      req_width: 1120
      req_height: 856
      skip_random: true

    # mosaic
    - id: mosaic
      name: 'NCSA Mosaic'
      os: 'Linux'
      version: '2.2'
      icon: 'mosaic.png'
      path: mosaic
      about: 'https://en.wikipedia.org/wiki/Mosaic_%28web_browser%29'

    # netscape 
    - id: netscape
      name: 'Netscape Navigator'
      os: 'Linux'
      version: '4.79'
      icon: 'win32-ns4.png'
      path: nslinux
      about: 'https://en.wikipedia.org/wiki/Netscape_%28web_browser%29'

    - id: netscape4.8-win
      name: 'Netscape Navigator'
      os: 'Windows'
      version: '4.8'
      icon: 'win32-ns4.png'
      path: nswin
      about: 'https://en.wikipedia.org/wiki/Netscape_%28web_browser%29'
    
    - id: netscape-mac-3.04
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '3.04'
      icon: 'mac-ns2-3.png'
      path: nsmac3
      about: 'https://en.wikipedia.org/wiki/Netscape_%28web_browser%29'

    - id: netscape-mac-4.08
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '4.08'
      icon: 'mac-ns4.png'
      path: nsmac4
      about: 'https://en.wikipedia.org/wiki/Netscape_%28web_browser%29'

    - id: netscape4.8-mac
      name: 'Netscape Navigator'
      os: 'Macintosh'
      version: '4.8'
      icon: 'mac-ns4.png'
      path: nsmac4.8
      about: 'https://en.wikipedia.org/wiki/Netscape_%28web_browser%29'

    # Internet Explorer
    - id: ie4.01-mac
      name: 'Internet Explorer'
      os: 'Macintosh'
      version: '4.01'
      icon: 'mac-ie4.png'
      path: ie4mac
      about: 'https://en.wikipedia.org/wiki/Internet_Explorer_for_Mac#Internet_Explorer_4.0_for_Macintosh'

    - id: ie5.1-mac
      name: 'Internet Explorer'
      os: 'Macintosh'
      version: '5.1.7'
      icon: 'mac-ie5.1.png'
      path: ie5mac
      about: 'https://en.wikipedia.org/wiki/Internet_Explorer_for_Mac#Internet_Explorer_5_Macintosh_Edition'

    - id: ie4
      name: 'Internet Explorer'
      os: 'Windows'
      version: '4.01'
      icon: 'win32-ie4.png'
      path: ie4
      about: 'https://en.wikipedia.org/wiki/Internet_Explorer_4'

    - id: ie5.5
      name: 'Internet Explorer'
      os: 'Windows'
      version: '5.5'
      icon: 'win32-ie5.5.png'
      path: ie5.5
      about: 'https://en.wikipedia.org/wiki/Internet_Explorer_5'


    # Safari
    - id: safari3
      name: 'Apple Safari'
      os: 'Windows'
      version: '3.2.3'
      icon: 'safari.png'
      path: safari
      about: 'https://en.wikipedia.org/wiki/Safari_(web_browser)#Safari_3'

    - id: safari5
      name: 'Apple Safari'
      os: 'Windows'
      version: '5.0'
      icon: 'safari.png'
      path: safari5
      about: 'https://en.wikipedia.org/wiki/Safari_%28web_browser%29#Safari_5'

