version: '2'

services:
    shepherd:
        build: ./shepherd

        environment:
            - REDIS_BROWSER_URL=redis://redis/0
            - CLUSTER_NAME=browser_shepherd
            - NETWORK_NAME=browsers_default

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 9020:9020

    redis:
        image: redis:2.8.21


