# WR Browser Engine Config
browser_config:
    api_version: '1.24'
    vnc_port: 6080
    cmd_port: 6082

    max_containers: 100

    init_container_expire_secs: 30
    full_container_expire_secs: 600

    throttle_max_avg: 0.60
    throttle_samples: 10
    throttle_expire_secs: 60

    queue_expire_secs: 30
    remove_expired_secs: 30

    browser_image_prefix: webrecorder/browser-
    network_name: webrecorder_browsers
    volume_source: webrecorder_browser_volumes_1

    default_browser: ch-53-lin

    browsers:
        -
            id: ch-53-lin
            image_name: chrome
            name: Chrome
            os: linux
            version: '53'
            release: '2016-09-30'
            icon: 'firefox.png'
            about: 'https://en.wikipedia.org/wiki/Firefox'
            capabilities:
                - flash
                - mp3
        -
            id: ff-49-lin
            image_name: firefox
            name: Firefox
            os: linux
            version: '49'
            release: '2016-09-23'
            icon: 'chrome.png'
            about: 'https://en.wikipedia.org/wiki/Google_Chrome'
            capabilities:
                - flash


