# WR Browser Engine Config
browser_config:
    api_version: '1.24'
    vnc_port: 6080
    cmd_port: 6082

    max_containers: 100

    throttle_max_avg: 0.60
    throttle_samples: 10
    throttle_expire_secs: 60

    container_expire_secs: 600
    req_expire_secs: 30
    queue_expire_secs: 30
    remove_expired_secs: 30

    browser_image_prefix: webrecorder/browser-
    label_name: wr.shepherd_name
    label_browser: wr.browser
    label_prefix: wr.

    default_browser: chrome

