# WR Browser Engine Config
browser_config:
    api_version: '1.24'
    vnc_port: 6080
    cmd_port: 6082

    max_containers: 100

    init_container_expire_secs: 30
    full_container_expire_secs: 600

    throttle_max_avg: 0.60
    throttle_samples: 10
    throttle_expire_secs: 60

    queue_expire_secs: 30
    remove_expired_secs: 30

    browser_image_prefix: webrecorder/browser-
    network_name: webrecorder_browsers
    volume_source: webrecorder_browser_volumes_1
    label_browser: wr.browser
    label_prefix: wr.

    default_browser: ch-53-lin

    label:
